### PR TITLE
Incorporating 2018 data for KCHA and SHA loads

### PR DESCRIPTION
**Pull request by alastairmatheson**
Updated code to accommodate 2018 data but also made several other changes to the existing approach for steps 1 and 2 in the data processing. Most of these changes were to standardize the naming of files/fields or for some speed improvements.

### CODE REVIEW

**Comment by alastairmatheson** [comment]
@jmhernan Here's where I got to with the steps 1 and 2 changes. I don't think anything of them would break your code (more than was already done) but it might be a good idea to check before I merge this.

**Comment by jmhernan** [comment]
> @jmhernan Here's where I got to with the steps 1 and 2 changes. I don't think anything of them would break your code (more than was already done) but it might be a good idea to check before I merge this.

I'll check on this. As soon as I can.

**Comment by jmhernan** [comment]
@alastairmatheson It seems like we only have one of these updates:

https://github.com/jmhernan/Housing/blob/als_dev/processing/02_sha_sql_load.R#L68-L80

How do I know which one we have? We only received two files and the columns look like sha3a, in particular, the `PK_HSUM`.

**Comment by alastairmatheson** [comment]
You only have 2 2018 files? If they're both CSVs then probably sha3a (and b?) The 2018 5a came as an xlsx for me.

> @alastairmatheson It seems like we only have one of these updates:
> 
> https://github.com/jmhernan/Housing/blob/als_dev/processing/02_sha_sql_load.R#L68-L80
> 
> How do I know which one we have? We only received two files and the columns look like sha3a, in particular, the `PK_HSUM`.

**Comment by jmhernan** [comment]
> You only have 2 2018 files? If they're both CSVs then probably sha3a (and b?) The 2018 5a came as an xlsx for me.
> 
> > @alastairmatheson It seems like we only have one of these updates:
> > https://github.com/jmhernan/Housing/blob/als_dev/processing/02_sha_sql_load.R#L68-L80
> > How do I know which one we have? We only received two files and the columns look like sha3a, in particular, the `PK_HSUM`.

Yes a csv "a" file and a "b" file. sorry for not clarifying.

**Comment by jmhernan** [comment]
@alastairmatheson I'm working on these conflicts right now and will have a branch that incorporates the uwdev pipe and your current updates.

**Comment by jmhernan** [comment]
Hi @alastairmatheson are you still working on the development of step07?  I made a copy of your most current work yesterday afternoon and step 7 changed a bit and is definitely giving me weird numbers. (300,000 cases in the end) with step 7 taking considerably more time to run (1.3 hours).

**Comment by jmhernan** [comment]
> Hi @alastairmatheson are you still working on the development of step07? I made a copy of your most current work yesterday afternoon and step 7 changed a bit and is definitely giving me weird numbers. (300,000 cases in the end) with step 7 taking considerably more time to run (1.3 hours).

Ignore this, I just read your commit message.  I will stick with the old step 07 until these changes are tested.  I will submit a PR with the integrated parts to the master once I'm done incorporating. Thanks!

**Comment by alastairmatheson** [comment]
@jmhernan I'm done with steps 7 and 8. I end up with 346,252 rows though your results might differ slightly due to the different inputs.

**Comment by jmhernan** [comment]
> @jmhernan I'm done with steps 7 and 8. I end up with 346,252 rows though your results might differ slightly due to the different inputs.

I am waiting on a data patch from SHA.  We are missing a critical column `familymemeberssn`.  We recently received data up until the end of 2018.  Is that what you have?

**Comment by alastairmatheson** [comment]
> > @jmhernan I'm done with steps 7 and 8. I end up with 346,252 rows though your results might differ slightly due to the different inputs.
> 
> I am waiting on a data patch from SHA. We are missing a critical column `familymemeberssn`. We recently received data up until the end of 2018. Is that what you have?

Yes, we have data through the end of 2018.

**Comment by jmhernan** [comment]
@alastairmatheson Ran through the code and I end up with way more cases 413,173.  We got weird SHA 2018 updates that contain some income data but they are not the usual 5b + 3b uploads. Not sure where to start looking. I might reduce our sha loads to the columns we need, this might help get rid of cases where for example, there are mutated income columns in SHA that change (i think some get appended with `.y` or `.x`) and when you bind the columns even if one exists in the new data it doesn't have the `.y` or `.x` and thus creates new columns were there shouldn't be any. We def are getting data with columns that don't match. Thoughts?

**Pull request merged**
