### PR TITLE
Uw data pipeline call dev

### PR DESCRIPTION
**Pull request by jmhernan**
@alastairmatheson, I managed to incorporate your changes on this branch.  This branch also incorporates the new data that we received last summer.  I followed the same format as before when we had specific uw code chunks:
```
if (UW == TRUE) {
run something
} else {
run original
}
```
There are other variables that I am introducing that are specific to python (since our pipeline is ran using a python script.  
The `metadata` file also might need some updated but I haven't touched that.  You mentioned you had some updates too. If you see anything funky, please let me know I am open to your input.

Thanks for collaborating with us.

Jose

### CODE REVIEW

**Comment by jmhernan** [comment]
@alastairmatheson Hi Alastair, my last run messed up something with our SHA counts and need to find the bug.  Please hold on merging. I will turn it into a WIP.

**Comment by jmhernan** [comment]
Its an error on my side I believe. Sorry about that. Is there any way we can check what you get on your end after step 8 in terms of row counts.

**Comment by alastairmatheson** [comment]
> Its an error on my side I believe. Sorry about that. Is there any way we can check what you get on your end after step 8 in terms of row counts.

A quick look shows 341,947 rows when I read in the file created at the end of step 8

**Comment by jmhernan** [comment]
Interesting, that number is good, I'm thinking now that we might be using different data...I'll keep digging. Thanks!

**Comment by alastairmatheson** [comment]
I think you received some different income/asset data recently, right? That could be throwing things off.

**Comment by jmhernan** [comment]
> I think you received some different income/asset data recently, right? That could be throwing things off.

I'll Check on that! Thanks!

**Comment by jmhernan** [comment]
> I think you received some different income/asset data recently, right? That could be throwing things off.

@alastairmathesonwhat would be the reason why the income /asset data is throwing things off?  Is it due to the join that happens between the assets/income and the rest of the data?

**Comment by alastairmatheson** [comment]
Correct, if the income isn't collapsed to a single row per person then it would lead to duplicate rows. However, the consolidation steps should take care of that, so I'm not actually sure why you're getting difference counts.

**Comment by jmhernan** [comment]
@alastairmatheson could we be using different data completely? I'm compiling a csv file with raw data descriptives (columns and row counts, year spans). I sent you a note about meeting about this, that would be super helpful if possible.

**Comment by jmhernan** [comment]
@alastairmatheson Hi.I'm experiencing a bottleneck in step 2 which wasn't there last week.  I'm thinking it might have to do with a dplyr update, can you run this step when you get a chance and see if you get stuck there as well?
```
multi_hoh <- sha %>%
  group_by(hh_id_temp) %>%
  summarise(people = n_distinct(hh_ssn, hh_lname, hh_lnamesuf, hh_fname, hh_mname)) %>%
  ungroup() %>%
  filter(people > 1) %>%
  mutate(rowcheck = row_number())
```
https://github.com/PHSKC-APDE/Housing/blob/master/processing/02_sha_sql_load.R#L804-L811

**Comment by alastairmatheson** [comment]
This worked ok for me. I'm still on 0.7.7 on dplyr though. I can update and retest later.

> @alastairmatheson Hi.I'm experiencing a bottleneck in step 2 which wasn't there last week. I'm thinking it might have to do with a dplyr update, can you run this step when you get a chance and see if you get stuck there as well?
> 
> ```
> multi_hoh <- sha %>%
>   group_by(hh_id_temp) %>%
>   summarise(people = n_distinct(hh_ssn, hh_lname, hh_lnamesuf, hh_fname, hh_mname)) %>%
>   ungroup() %>%
>   filter(people > 1) %>%
>   mutate(rowcheck = row_number())
> ```
> 
> https://github.com/PHSKC-APDE/Housing/blob/master/processing/02_sha_sql_load.R#L804-L811

**Comment by jmhernan** [comment]
> This worked ok for me. I'm still on 0.7.7 on dplyr though. I can update and retest later.

It worked after I updated to the latest dplyr_0.8.1.9000

**Comment by jmhernan** [comment]
@alastairmatheson this is ready.

**Comment by jmhernan** [comment]
I added a commented variable `housing_source_dir` where your local metadara.json file should live, we don't need to pass this on our end since we are sourcing from the terminal and pass it as a variable in python, but you will have to specify locally.

**Pull request merged**
